name: Release

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:
    branches: ["release-*"]
  workflow_dispatch:
    inputs:
      chain_key:
        description: "chain key to use for testing"
        required: false
        default: 'ethereum-sepolia-prod'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  pull-requests: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  RISC0_TOOLCHAIN_VERSION: 1.85.0
  RISC0_CRATE_VERSION: "2.1.0"
  FOUNDRY_VERSION: v1.0.0

jobs:
  deployment:
    runs-on: [ self-hosted, prod, "${{ matrix.os }}", "${{ matrix.device }}" ]
    strategy:
      # Run only on Linux with CPU.
      matrix:
        include:
          - os: Linux
            feature: default
            device: cpu
    env:
      RPC_MAP: |
        {
          "ethereum-sepolia-prod": "https://ethereum-sepolia-rpc.publicnode.com",
          "ethereum-sepolia-staging": "https://ethereum-sepolia-rpc.publicnode.com",
          "base-sepolia-prod": "https://base-sepolia-rpc.publicnode.com",
          "base-sepolia-staging": "https://base-sepolia-rpc.publicnode.com",
          "base-mainnet": "https://base-rpc.publicnode.com"
        }
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: ${{ env.FOUNDRY_VERSION }}

      - uses: risc0/risc0/.github/actions/rustup@352dea62857ba57331053cd0986a12c1a4708732
      
      - uses: risc0/risc0/.github/actions/sccache@352dea62857ba57331053cd0986a12c1a4708732
        with:
          key: ${{ matrix.os }}-${{ matrix.feature }}

      - name: install cargo risczero
        uses: ./.github/actions/bininstall-risc0
        with:
          risczero-version: '2.1.0'
          toolchain-version: '1.85.0'

      - name: forge build
        run: forge build

      - name: cargo install boundless-cli
        run: cargo install boundless-cli --path crates/boundless-cli --locked

      - name: forge deployment test
        env:
          CHAIN_KEY: ${{ github.event.inputs.chain_key }}
          FOUNDRY_PROFILE: deployment-test
          RPC_URL: ${{ fromJson(env.RPC_MAP)[github.event.inputs.chain_key] }}
        run: forge test -vvv --fork-url="$RPC_URL"


      - name: sccache stats
        run: sccache --show-stats
